version: 1
jobs:
  compile: 
    image: node
    script:
      - npm install @nomiclabs/buidler @nomiclabs/buidler-truffle5 @nomiclabs/buidler-web3 web3
      - npm install
      - npx builder compile
test:
  image: node
  script: 
    - npm install @nomiclabs/buidler @nomiclabs/buidler-truffle5 @nomiclabs/buidler-web3 web3
    - npm install
    - npx buidler test
stages:
  - pipeline:
      jobs:
        - compile
        - test